#服务器配置
server:
  port: 8081
  servlet:
    session:
      timeout: 3600s
    context-path: /iters
  max-http-header-size: 10000000
spring:
  application:
    name: iters
  #时间格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #接收时间类型参数
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: datasource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/iters?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=PRC&useSSL=false
      username: root
      password: 123456
      initial-size: 2
      min-idle: 2
      max-active: 30
      max-wait: 10000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      web-stat-filter:
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/*.json,/druid/*
      connection-init-sqls: SET NAMES utf8mb4;
  thymeleaf:
    prefix: classpath:/templates/
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
#mybatis
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml,classpath*:/mapper/*/*.xml
  global-config:
    db-config:
      db-type: mysql
      id-type: ID_WORKER_STR
      logic-delete-value: -1
      logic-not-delete-value: 1
    banner: false
  type-aliases-package: com.xinghui.entity
  type-enums-package: com.xinghui.enums

## 日志
logging:
  level:
    com:
      xinghui: debug

file:
  filepaths: http://127.0.0.1:88/staticUp/
  uploadpath: D\:\\Upload&staticUp
#邮箱配置
mail:
  spring.mail.host: smtp.qq.com
  spring.mail.username: 1101225081@qq.com
  spring.mail.password: glblvsldinymgbhi
  spring.mail.default-encoding: UTF-8
  spring.mail.port: 465
  spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  spring.mail.properties.mail.debug: true
#支付配置
alipay:
  appID: 2016101300679839
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPhlmFqekNyod94wPloBKeorRFFQ4o0aC2h+OCHtUKCW6xfHwxQnT76447XIY33AjLQ+tH7o2yNEIINKu4G7pp4wpxHup5h9rWf6UmmH7eqvAa6jr+hXfjhqAKWkVnUDLDqRh3k+G+L5ACPm09dP4rT5XnsOFSHWqSyBnQwkMQt6+v8YNpCM5NdCzqKxyzvsacdbeUxim7f61TG88XxOfvzFC8cz+/vLvxXQFSy/Rb0RZkoQiAZQivDNgAAc1qXuqAbDU61Uy3I/FpaizGS2tFAuBagHjavc72ful+xCyNh/rofp84NmyVlt7u6fuWrqNtebLC9PrPkUeeyjNpKoNzAgMBAAECggEASvOlJaeGatq5MPhrEeZMk0sEfObr5EZCG2rc+sQUAboCZswlNs1f3xTmm/4A4+/upSt0sNgyCSjiqIANfUNWgqPjw5N88EPnAA2+IkB1ogpvCemLQR4HfP/Ekbik1HmcvBo4ogehQsV+57CQV+AHZLEr3TB/UN8a/MSUvldLTZ/DSFjGtWbR/ki452mj/b4ocnwCZimBFB4jA2IUnSIX2AeGg8LJNojqLcFL3h2QD2DCWk/zhlzPFmgD7D0RhbhmdS7o7D1Stb9KC4Gtpj7ExIsi2tPr1HwvhdJVM6p6wu4o4RTN9p/5OBc/oLl41gemPW0xyPi8LnNZaxAcqGiZsQKBgQD3GLQTqMrq6IbKz3D8/ktKZg8NXVXO/zj3m17Kr2fC90zGYLevXA28plvMLfzw2Uv/slnweVepk4m2t01kdIl328lMU5hDxxAwOVFm/3sR369Mr6iukwlgMabtu3urQby+LZw92a6N4C7JmcUv0lXassx+5YxZZ3DYNqNrENNADwKBgQDXAJ/YVW8l5ZnVF5AlH4bXuaxT+Q6MYdMq8KMU/D7k4J/qcyqVi3uYR7NtbvGDS08wDsR9NnwgfrLuMH07hvSSkxnFBuzAvpB61gd/rBLf3Cq5C7Jyx3/IiVbLIwvIbKQb97ahtI6TweHpKbKA+SRpwjBFma1cTic6iWy3xTHiXQKBgF/FMl6ASI29rCjFOBzGjvX6EpFygISnRTQrAxV54LSfVyF4cRlFi4l3zRKZLHVJM3yaauOalFCEf5bS+usZhAJxrFap+9UhPXQDczqBgPjPgsktOCrZkIO5GuL/jJI2+2mWkf0i9tXEcz3uHJBJbL9EF6CDZd9tCT60BqjDr60fAoGAIs+MEefLRjSFkrXs9cXD/FuopjP2Ag64tQQfM3+f40jnO3uIEoxx53b8eyRyYBKqcJqDf855jH1XFS+upxuzr6O3kWoMnSx9khXjQu2mZK5uEGXvb5wTeXGbJuq2tq24aHrUDByC1TOYEztYFn/AQItba3l1UzOoMFcdzidUa1UCgYEAtFJGtpC1sCrAPJgDTosGA5PqVWDvIQJuhYwHFo0FYTBWt7/c7oVzcGcoMWIoA6D2FxLwO0zJRTy8CmLF+PzLSFUizOmbyygqtLjRD+vjCEbavP/wOKqiDmFcDEtbBCWaI3aUA0X+onx2GUFEdKZWhE06LzwYA4i145xVOnwqXG0=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4ZZhanpDcqHfeMD5aASnqK0RRUOKNGgtofjgh7VCglusXx8MUJ0++uOO1yGN9wIy0PrR+6NsjRCCDSruBu6aeMKcR7qeYfa1n+lJph+3qrwGuo6/oV344agClpFZ1Ayw6kYd5Phvi+QAj5tPXT+K0+V57DhUh1qksgZ0MJDELevr/GDaQjOTXQs6iscs77GnHW3lMYpu3+tUxvPF8Tn78xQvHM/v7y78V0BUsv0W9EWZKEIgGUIrwzYAAHNal7qgGw1OtVMtyPxaWosxktrRQLgWoB42r3O9n7pfsQsjYf66H6fODZslZbe7un7lq6jbXmywvT6z5FHnsozaSqDcwIDAQAB
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  sysServiceProviderId: 1234
  notifyUrl: http://localhost:8081/iters/notify_url